rabbitmq:
  exchange: "DisplayExchange"
  host: "192.168.88.22"
  port: 5672
  username: "admin"
  password: "1"
  queues:
    scannerQueue: "BarcodeQueue"
    displayQueue: "DisplayQueue"
    scaleQueue: "ScaleQueue"
  routingKeys:
    scannerKey: "BarcodeRoutingKey"
    displayKey: "DisplayRoutingKey"
    scaleKey: "ScaleRoutingKey"
  timeouts:
    heartbeat: 60
    networkRecover: 1
    connection: 10

devicesPort:
  cubic:
    enabled: yes
    port: "COM12" #Сканер-Кубик
  handheld:
    enabled: yes
    port: "COM10" #Ручной сканер
  scales:
    enabled: yes
    port: "COM5" #Весы
  scalesScanner:
    enabled: yes
    port: "COM1" #Встроенный сканер в весовую платформу
  display:
    enabled: yes
    port: "COM8" #Дисплей покупателя