rabbitmq:
  exchange: "DisplayExchange"
  host: "10.200.202.245"
  port: 5672
  username: "admin"
  password: "1"
  queues:
    scannerQueue: "BarcodeQueue"
    displayQueue: "DisplayQueue"
    scaleQueue: "ScaleQueue"
  routingKeys:
    scannerKey: "BarcodeRoutingKey"
    displayKey: "DisplayRoutingKey"
    scaleKey: "ScaleRoutingKey"
  timeouts:
    heartbeat: 60
    networkRecover: 1
    connection: 10

devicesPort:
  cubic:
    enabled: yes
    port: "COM9" #Сканер-Кубик
  handheld:
    enabled: yes
    port: "COM13" #Ручной сканер
  scales:
    enabled: yes
    port: "COM15" #Весы
  scalesScanner:
    enabled: yes
    port: "COM17" #Встроенный сканер в весовую платформу
  display:
    enabled: yes
    port: "COM11" #Дисплей покупателя